Added: 	- -v|--version for displaying version information. 	- Extended compatibilty across distros (Ubuntu, Debian, Raspbian, Fedora, CentOS, openSUSE (Leap & Tumbleweed).
Changed:
	- Debian package description.
	- unitName replaces gniUnit, to avoid confusion and match closer with uploadnewip.
	- Root group now owns the unit config file, 0600 permissions.
	- Test mode now overrides the same IP address (as it's supposed to).

Fixed:
	- Correctly written bash instructions.
	- Now properly removes one or multiple given unit(s).
	- Permissions for units, to avoid errors -- In some distros users don't have groups of the same name.

diff --git a/getnewip b/getnewip
--- a/getnewip
+++ b/getnewip
@@ -3,7 +3,7 @@
 # getnewip
 
 #
-# Copyright (C) 2018 Caleb Woodbine <github.com/BobyMCbobs>
+# Copyright (C) 2018 Caleb Woodbine <gitlab.com/BobyMCbobs>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -20,7 +20,7 @@
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #
 
-VERSION=2.1.2
+VERSION=2.2
 
 function helpMenu() {
 #print help menu
@@ -110,7 +110,7 @@ Amount of time until curl requests drops:
 
 	*)
 echo "------------------------
-Usage: getnewip -[n,s,t] [config file]
+Usage: getnewip -[n,s,t] [unit config file]
 
 Running Modes:
 	-n|--no-loop|-o|--once		perform a single check and exit.
@@ -137,9 +137,16 @@ esac
 
 }
 
+function printVersion() {
+# print simple version information
+
+echo "getnewip v$VERSION"
+
+}
+
 function getDefaultUnitConfig() {
 
-echo "gniUnit=''				## name of unit i.e mainServer, workServer, serverAtHome -- pretty name for config unit.
+echo "unitName=''				## mainServer, workServer, serverAtHome, etc. A pretty name which is the same as a unit used with uploadnewip.
 localReferenceDevice=''			## Address of local server: xxx.xxx.xxx.xxx (i.e 192.168.0.1).
 localTestPorts=()			## open local ports to test from localReferenceDevice. i.e: (22 80 443) etc...
 portCheckTimeOut=			## amount of time to wait until stop checking if port is active i.e: 3 (seconds).
@@ -160,7 +167,7 @@ portCheckTimeOut=
 pingServer=''
 SSHcfgHost=('')
 dropboxFolder=''
-gniUnit=''
+unitName=''
 dropboxAppKey=''
 includedUsers=('')
 
@@ -169,11 +176,11 @@ includedUsers=('')
 function main() {
 # main funtion that runs
 
-if $fetchIPNoCheck
+if ! $changeIPRegardless
 then
 	connectionTest && checkIfNotAtLocalDevice
 
-elif ! $fetchIPNoCheck
+elif $changeIPRegardless
 then
 	IPfromDB
 fi
@@ -185,11 +192,11 @@ function connectionTest() {
 if ping -q -c 1 -W 1 $pingServer > /dev/null
 then
   	# if internet is up
-	echo "> Can ping '$pingServer' for unit '$gniUnit'."
+	echo "> Can ping '$pingServer' for unit '$unitName'."
 	return 0
 else
   	# if internet is down
-	echo ">> Can't ping '$pingServer' for unit '$gniUnit'."
+	echo ">> Can't ping '$pingServer' for unit '$unitName'."
 	return 1
 fi
 }
@@ -200,14 +207,19 @@ function checkIfNotAtLocalDevice() {
 capturePortActive=()
 capturePortNum=0
 
-for port in ${localTestPorts[@]}
+for port in "${localTestPorts[@]}"
 do
-	localPortTest=$(nc -zv -w3 $localReferenceDevice $port 2>&1)
+	localPortTest=$(nc -zv -w3 "$localReferenceDevice" "$port" 2>&1)
 	capturePortActive+=($?)
 	[ "${capturePortActive[-1]}" = 0 ] || echo ">> Port: '$port' closed." && capturePortNum=$((capturePortNum+=1))
 done
 
-[ ! $capturePortNum = ${#localTestPorts[@]} ] && echo ">> '$gniUnit' config not completing, because not all ports suggested of '$localReferenceDevice' were open." || IPfromDB
+if [ ! $capturePortNum = ${#localTestPorts[@]} ]
+then
+	echo ">> '$unitName' config not completing, because not all ports suggested of '$localReferenceDevice' were open."
+else
+	IPfromDB
+fi
 
 }
 
@@ -216,7 +228,7 @@ function IPfromDB() {
 
 echo "> Downloading copy of IP from dropbox."
 tmpFile="/tmp/getnewip-response-$RANDOM-temp"
-newIPnum=$(curl -m $curlTimeoutTime --progress-bar -X POST --globoff -D "$tmpFile" --header "Authorization: Bearer $dropboxAppKey" --header "Dropbox-API-Arg: {\"path\": \"/$dropboxFolder/currentip-$gniUnit.txt\"}" "https://content.dropboxapi.com/2/files/download")
+newIPnum=$(curl -m $curlTimeoutTime --progress-bar -X POST --globoff -D "$tmpFile" --header "Authorization: Bearer $dropboxAppKey" --header "Dropbox-API-Arg: {\"path\": \"/$dropboxFolder/currentip-$unitName.txt\"}" "https://content.dropboxapi.com/2/files/download")
 checkHttpResponse
 
 if [[ $newIPnum =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
@@ -235,7 +247,7 @@ fi
 function checkHttpResponse() {
 # verify if response was successful
 
-local response
+local response tempFile
 response=$?
 
 if [ ! $response = 0 ]
@@ -243,7 +255,10 @@ then
 	echo ">> Failed to access dropbox in some way." && return 1
 fi
 
-[[ -f /tmp/getnewip-response-*-temp ]] && rm /tmp/getnewip-response-*-temp
+for tempFile in $(command ls /tmp/getnewip-response-*-temp)
+do
+	[ -f "$tempFile" ] && rm "$tempFile"
+done
 return 0
 
 }
@@ -253,7 +268,7 @@ function modifySSHConfig() {
 
 local user SSHconfigFileLocation
 
-for user in ${includedUsers[@]}
+for user in "${includedUsers[@]}"
 do
 	homeDir=$(echo $(getent passwd $user )| cut -d : -f 6)
 	[ -z $homeDir ] && echo ">> Could not find home directory of user '$user'."
@@ -262,7 +277,7 @@ do
 		SSHconfigFileLocation=$homeDir/.ssh/config
 		if [ -f $SSHconfigFileLocation ]
 		then
-			for givenHost in ${SSHcfgHost[@]}
+			for givenHost in "${SSHcfgHost[@]}"
 			do
 				oldIPnum=$(ssh -G $givenHost | grep -i "HostName " | head -n 1 | cut -d" " -f2)
 				[[ $(id -g) = 0 ]] && oldIPnum=$(su $user -c "ssh -G $givenHost | grep -i 'HostName ' | head -n 1 | cut -d' ' -f2")
@@ -270,7 +285,7 @@ do
 				[[ ! ${#includedUsers[@]} = 1 ]] && echo "> Updating '$user'."
 				[[ -z $oldIPnum ]] && echo ">> Invalid host '$givenHost'." && return 1
 
-				if [ ! $oldIPnum = $newIPnum ]
+				if [ ! $oldIPnum = $newIPnum ] || $changeIPRegardless
 				then
 					echo "> Host '$givenHost': Changing IP from $oldIPnum to $newIPnum in config"
 					sed -i -e "s/$oldIPnum/$newIPnum/g" $SSHconfigFileLocation || echo ">> Failed to update IP for '$givenHost' for user '$user'."
@@ -292,12 +307,20 @@ function variableCheck() {
 # check for empty variables in config file
 
 local pt users host port digit
-opt=$@
+opt="$@"
 users=$(awk -F'[/:]' '{if ($3 >= 1000 && $3 != 65534) print $1}' /etc/passwd)
 digit=[0-9]
 
 local var
-if [[ -z $localReferenceDevice || -z ${localTestPorts[@]} || -z $portCheckTimeOut || -z ${SSHcfgHost[@]} || -z $dropboxFolder || -z $gniUnit || -z $dropboxAppKey || -z ${includedUsers[@]} || -z $pingServer ]]
+if [[ -z $localReferenceDevice ]] || \
+   [[ -z "${localTestPorts}" ]] || \
+   [[ -z $portCheckTimeOut ]] || \
+   [[ -z "${SSHcfgHost}" ]] || \
+   [[ -z $dropboxFolder ]] || \
+   [[ -z $unitName ]] || \
+   [[ -z $dropboxAppKey ]] || \
+   [[ -z "${includedUsers}" ]] || \
+   [[ -z $pingServer ]]
 then
 	[ -z $opt ] && echo ">> Please fill in all required variabled -- Edit '/etc/getnewip/units/$configFile'." && exit 1
 	return 1
@@ -305,11 +328,11 @@ else
 	[ ! "${#dropboxAppKey}" = 64 ] && echo ">> Dropbox key invalid." && return 1
 	[[ ! $portCheckTimeOut =~ $digit ]] && echo ">> 'portCheckTimeOut' must be a number." && return 1
 	[[ ! $pingServer =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] && echo ">> 'pingServer' must be a valid IPv4 address." && return 1
-	for port in ${localTestPorts[@]}
+	for port in "${localTestPorts[@]}"
 	do
 		[[ ! $port =~ $digit ]] && return 1
 	done
-	for user in ${includedUsers[@]}
+	for user in "${includedUsers[@]}"
 	do
 		homeDir=$(echo $(getent passwd $user ) | cut -d : -f 6)
 		if ! echo $users | grep -q -w $user
@@ -317,7 +340,7 @@ else
 			echo ">> Could not find user '$user'."
 			return 1
 		else
-			for host in ${SSHcfgHost[@]}
+			for host in "${SSHcfgHost[@]}"
 			do
 				! grep -q -w $host $homeDir/.ssh/config && echo ">> Cannot find SSH config file for user '$user'." && return 1
 			done
@@ -334,7 +357,7 @@ function configLoad() {
 local configFiles
 configFiles="$@"
 
-echo ${configFiles[@]} | grep -q -w 'getnewip-example' && helpMenu config
+echo "${configFiles[@]}" | grep -q -w 'getnewip-example' && helpMenu config
 
 for configFile in $configFiles
 do
@@ -357,12 +380,12 @@ function listConfigUnits() {
 # list all available units' config files
 
 local unit opt out counter
-opt=$@
+opt="$@"
 counter=0
 
 [ ! -d /etc/getnewip/units ] && echo ">> Failed to find units folder." && exit 1
 
-for unit in $(ls /etc/getnewip/units)
+for unit in $(command ls /etc/getnewip/units)
 do
 	counter=$((counter+=1))
 	out="$unit $out"
@@ -388,7 +411,7 @@ fi
 function makeNewConfigUnit() {
 # create a new unit file
 
-local user
+local user file
 user=$(whoami)
 
 if [ ! -f $tempFile ] || [ -z $tempFile ]
@@ -406,7 +429,7 @@ echo "
 	q) [Q]uit without saving.
 "
 
-read -p ": " continuevar
+read -r -p ": " continuevar
 echo
 case $continuevar in
 	0|e|E)
@@ -422,7 +445,7 @@ case $continuevar in
 	2|s|S)
 		if . $tempFile && variableCheck a
 		then
-			$sudoProg install -g $user -o $user -m 0600 $tempFile /etc/getnewip/units/$gniUnit.conf && echo "> Config '$gniUnit' saved." && exit 0
+			$sudoProg install -g root -o $user -m 0600 $tempFile /etc/getnewip/units/$unitName.conf && echo "> Config '$unitName' saved." && exit 0
 			echo ">> Failed to write config." && [ -f $tempFile ] && rm $tempFile && echo "> Cleaned up temporary files."  && exit 1
 		else
 			echo ">> Variables not set correctly. Please fix them." && sleep 1 && makeNewConfigUnit
@@ -431,6 +454,10 @@ case $continuevar in
 
 	q|Q)
 		[ -f $tempFile ] && rm $tempFile && echo "> Cleaned up temporary files."
+		for file in /tmp/getnewip-unit-*-temp
+		do
+			[ -f $file ] && rm $file
+		done
 		exit 0
 	;;
 esac
@@ -446,9 +473,9 @@ then
 fi
 
 local unit
-if ! [[ -z ${disabledUnits[@]} ]]
+if ! [[ -z "${disabledUnits}" ]]
 then
-	for unit in ${disabledUnits[@]}
+	for unit in "${disabledUnits[@]}"
 	do
 		[ ! -f /etc/getnewip/units/$unit.conf ] && echo ">> Cannot find unit '$unit' to disable. Ignoring..."
 	done
@@ -460,11 +487,13 @@ fi
 }
 
 function removeUnit() {
-# remove a given unit
+# remove given units
 local unitFiles unit unitFullFileName
-unitFiles=$@
+unitFiles="$@"
 
 [[ -z $unitFiles ]] && echo ">> No configs given to remove. Run 'getnewip -l' for a list of units" && exit 1
+
+echo "> Preparing to remove '$unitFiles'."
 
 for unit in $unitFiles
 do
@@ -476,15 +505,12 @@ do
 		if rm -v /etc/getnewip/units/$unitFullFileName
 		then
 			echo "> Unit '$unit' removed."
-			echo "> Finished removal of unit '$unit'!"
-			exit 0
 		else
 			echo ">> Failed to remove unit '$unit'."
-			exit 1
+			return 1
 		fi
 	else
 		echo ">> Could not find unit '$unit'."
-		exit 1
 	fi
 done
 
@@ -559,7 +585,7 @@ case "$givenOpt" in
 		# no loop.
 		shift
 		readonly isLooped=false
-		readonly fetchIPNoCheck=true
+		readonly changeIPRegardless=false
 		echo "> Running single check."
 		startMain "$@"
 	;;
@@ -568,7 +594,7 @@ case "$givenOpt" in
 		# service mode, run as loop.
 		shift
 		readonly isLooped=true
-		readonly fetchIPNoCheck=true
+		readonly changeIPRegardless=false
 		echo "> Running in service mode."
 		echo ">> Date: $(date)."
 		startMain "$@"
@@ -578,7 +604,7 @@ case "$givenOpt" in
 		# fetch IP regardless, once.
 		shift
 		readonly isLooped=false
-		readonly fetchIPNoCheck=false
+		readonly changeIPRegardless=true
 		echo "> Running in test mode."
 		startMain "$@"
 	;;
@@ -603,6 +629,10 @@ case "$givenOpt" in
 		shift
 		helpMenu "$@"
 		exit
+	;;
+
+	-v|--version)
+		printVersion
 	;;
 
 	*)
