v2.1
Added:
	- Bash completion.
	- http response checking.
	- http response timeout with curl.
	- Settings config checking.
	- Easy unit removing.
	- More documentation.

Changed:
	- Home directories aren't assumed, now taken from passwd.
	- Service mode is now called daemon mode.
		- Use -d, instead of -s.
	- Building is now done in a fakeroot.

Fixed:
	- Unit config testing.
	- Bugs.

diff --git a/usr/bin/getnewip b/usr/bin/getnewip
--- a/usr/bin/getnewip
+++ b/usr/bin/getnewip
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-#getnewip
+# getnewip
 
 #
 # Copyright (C) 2018 Caleb Woodbine <github.com/BobyMCbobs>
@@ -20,34 +20,35 @@
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #
 
-#don't run unless owner is logged in
-checkIfUserIsLoggedIn=true
-
-VERSION=2.0
+VERSION=2.1
 
 function helpMenu() {
 #print help menu
+
+echo "getnewip (version: $VERSION)"
+
 local opt
 opt=$1
 case "$opt" in
 	config)
-echo "
+echo "-------------------------
 How to setup config files
--------------------------
 
-Every variable in the config files is important, unless regarded otherwise.
+Config files are just text files containing Bash variables.
 
 1 EASIEST) Run 'getnewip -m'
 
 2 Easy) Make a copy of '/etc/getnewip/getnewip-example.conf' into
 	   '/etc/getnewip/units/' as a new config file, and customise variables.
+
+Notes:
+	Every variable in the config files is important, unless regarded otherwise.
 "
 	;;
 
 	sshconfig)
-echo "
+echo "----------------
 SSH config files
-----------------
 
 What are they for:
 	SSH config files are a way of storing logins
@@ -59,13 +60,15 @@ Where:
 Basic contents of a file:
 	Host NICKNAME
 		HostName IPADDRESS
+
+Notes:
+	Read 'man ssh_config' to read indepth about SSH user config files.
 "
 	;;
 
 	service)
-echo "
+echo "--------------------
 Systemd service info
---------------------
 
 Default seutp:
 	By default, the service will
@@ -77,26 +80,49 @@ Location:
 	The service file is located at 'etc/systemd/system/getnewip.service'.
 	Note: You may need to reload the daemons after editing.
 
-Enable service:
-	'sudo systemctl enable getnewip.service'
+Control service:
+	Enable: 'systemctl enable getnewip'.
+	Start:'systemctl start getnewip'.
+	Status: 'systemctl status getnewip'.
 "
 	;;
 
+	settings)
+echo "--------------------
+Settings config info
+
+Where is it located?
+	/etc/getnewip/getnewip-settings.conf
+
+Disabling Units:
+	Add entries into 'disabledUnits=()'
+	i.e: disabledUnits=('server1' 'mainServer2' 'homeServer')
+
+Wait time between unit checking:
+	'loopDelayTime' relates to the amount of time that is slept between checking units.
+	Give it a reasonable amount of time, 600 (seconds) is default.
+
+Amount of time until curl requests drops:
+	'curlTimeoutTime' is a variable which dictates the amount of time that a curl request can last.
+	Default is '180' (which is 3 minutes).
+"
+;;
+
 	*)
-echo "getnewip (version: $VERSION)
-------------------------
+echo "------------------------
 Usage: getnewip -[n,s,t] [config file]
 
 Running Modes:
-	-n|--no-loop|-o|--once 		to not loop.
-	-s|--service	 		to run in service mode, looping.
+	-n|--no-loop|-o|--once		perform a single check and exit.
+	-d|--daemonise|--daemonize	to run in service mode, looping.
 	-t|--testmode			for test mode.
 	-l|--list			list available config files.
-	-m|--make			make a unit config file.
+	-m|--make-unit			make a unit config file.
 	-h|--help			print this menu.
-	  	  config		  get info on config files.
-		  sshconfig		  get info on setting up '~/.ssh/config'.
-		  service		  get info on systemd service.
+		config				get info on config files.
+		sshconfig			get info on setting up '~/.ssh/config'.
+		service				get info on systemd service.
+		settings			get settings on configuring getnewip.
 
 Config files:
 	Units:
@@ -112,24 +138,39 @@ esac
 
 function getDefaultUnitConfig() {
 
-echo "localReferenceDevice='' 		## Address of local server: xxx.xxx.xxx.xxx (i.e 192.168.0.1).
+echo "gniUnit=''				## name of unit i.e mainServer, workServer, serverAtHome -- pretty name for config unit.
+localReferenceDevice=''			## Address of local server: xxx.xxx.xxx.xxx (i.e 192.168.0.1).
 localTestPorts=()			## open local ports to test from localReferenceDevice. i.e: (22 80 443) etc...
 portCheckTimeOut=			## amount of time to wait until stop checking if port is active i.e: 3 (seconds).
 pingServer=''				## always up external server to ping. i.e: '8.8.8.8'.
 SSHcfgHost=('')				## .ssh/config host(s) to modify i.e serverRemote, homeserver.
 dropboxFolder=''			## dropbox app folder i.e ServerIP, IP, Addresses.
-gniUnit=''				## name of unit i.e mainServer, workServer, serverAtHome -- pretty name for config unit.
-dropboxAppKey=''			## dropbox app key -- It should be a 64 character string.
-includedUsers=('')			## user(s) to effect. i.e: ('jane' 'john' 'mark')"
+includedUsers=('')			## user(s) to effect. i.e: ('jane' 'john' 'mark')
+dropboxAppKey=''			## dropbox app key -- It should be a 64 character string."
+
+}
+
+function cleanVariables() {
+# clean/clear variables between checks
+
+localReferenceDevice=''
+localTestPorts=()
+portCheckTimeOut=
+pingServer=''
+SSHcfgHost=('')
+dropboxFolder=''
+gniUnit=''
+dropboxAppKey=''
+includedUsers=('')
 
 }
 
 function main() {
-#main funtion that runs
+# main funtion that runs
 
 if $fetchIPNoCheck
 then
-	internetTest
+	internetTest && checkIfNotAtLocalDevice
 
 elif ! $fetchIPNoCheck
 then
@@ -138,21 +179,22 @@ fi
 
 }
 
-function internetTest() {
-#test internet
+function connectionTest() {
+# test internet
 if ping -q -c 1 -W 1 $pingServer > /dev/null
 then
-  	#if internet is up
-	echo "> Internet is connected, continuing."
-	checkIfNotAtLocalDevice
+  	# if internet is up
+	echo "> Can ping '$pingServer' for unit '$gniUnit'."
+	return 0
 else
-  	#if internet is down
-	echo "> No internet, continuing."
+  	# if internet is down
+	echo ">> Can't ping '$pingServer' for unit '$gniUnit'."
+	return 1
 fi
 }
 
 function checkIfNotAtLocalDevice() {
-#check if connection is external from server
+# check if connection is external from server
 
 capturePortActive=()
 capturePortNum=0
@@ -169,36 +211,54 @@ done
 }
 
 function IPfromDB() {
-#download current IP from dropbox
+# download current IP from dropbox
 
 echo "> Downloading copy of IP from dropbox."
-tmpFile="/tmp/getnewip_du_resp_$RANDOM"
-newIPnum=$(curl --progress-bar -X POST --globoff -D "$tmpFile" --header "Authorization: Bearer $dropboxAppKey" --header "Dropbox-API-Arg: {\"path\": \"/$dropboxFolder/currentip-$gniUnit.txt\"}" "https://content.dropboxapi.com/2/files/download")
+tmpFile="/tmp/getnewip-response-$RANDOM-temp"
+newIPnum=$(curl -m $curlTimeoutTime --progress-bar -X POST --globoff -D "$tmpFile" --header "Authorization: Bearer $dropboxAppKey" --header "Dropbox-API-Arg: {\"path\": \"/$dropboxFolder/currentip-$gniUnit.txt\"}" "https://content.dropboxapi.com/2/files/download")
+checkHttpResponse
 
-if [[ $newIPnum =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || [ $? = 0 ]
+if [[ $newIPnum =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
 then
 	echo "> Downloaded IP successfully."
 	rm $tmpFile
 	modifySSHConfig
 else
-	echo "> Download Failed. Retrying."
-	sleep $loopDelayTime
+	echo ">> Download Failed. Retrying."
+	sleep 20s
 	IPfromDB
 fi
 
 }
 
+function checkHttpResponse() {
+# verify if response was successful
+
+local response
+response=$?
+
+if [ ! $response = 0 ]
+then
+	echo ">> Failed to access dropbox in some way." && return 1
+fi
+
+[[ -f /tmp/getnewip-response-*-temp ]] && rm /tmp/getnewip-response-*-temp
+return 0
+
+}
+
 function modifySSHConfig() {
-#change .ssh/config
+# change $HOME/.ssh/config
 
 local user SSHconfigFileLocation
 
 for user in ${includedUsers[@]}
 do
+	homeDir=$(echo $(getent passwd $user )| cut -d : -f 6)
+	[ -z $homeDir ] && echo ">> Could not find home directory of user '$user'."
 	if [[ $(whoami) = $user || $(id -g) = 0 ]]
 	then
-		#echo ">> Whoops, you're not '$user'. Only users who own their file can edit it." && exit
-		SSHconfigFileLocation=/home/$user/.ssh/config
+		SSHconfigFileLocation=$homeDir/.ssh/config
 		if [ -f $SSHconfigFileLocation ]
 		then
 			for givenHost in ${SSHcfgHost[@]}
@@ -212,9 +272,9 @@ do
 				if [ ! $oldIPnum = $newIPnum ]
 				then
 					echo "> Host '$givenHost': Changing IP from $oldIPnum to $newIPnum in config"
-					sed -i -e "s/$oldIPnum/$newIPnum/g" $SSHconfigFileLocation || echo ">> Failed to update IP."					
+					sed -i -e "s/$oldIPnum/$newIPnum/g" $SSHconfigFileLocation || echo ">> Failed to update IP for '$givenHost' for user '$user'."
 				else
-					echo "> Host '$givenHost': IP hasn't changed from '$oldIPnum', doing nothing."
+					echo "> Host '$givenHost': IP hasn't changed from '$oldIPnum', doing nothing..."
 				fi
 			done
 		else
@@ -230,9 +290,10 @@ done
 function variableCheck() {
 # check for empty variables in config file
 
-local opt users host
+local pt users host port digit
 opt=$@
 users=$(awk -F'[/:]' '{if ($3 >= 1000 && $3 != 65534) print $1}' /etc/passwd)
+digit=[0-9]
 
 local var
 if [[ -z $localReferenceDevice || -z ${localTestPorts[@]} || -z $portCheckTimeOut || -z ${SSHcfgHost[@]} || -z $dropboxFolder || -z $gniUnit || -z $dropboxAppKey || -z ${includedUsers[@]} ]]
@@ -240,16 +301,28 @@ then
 	[ -z $opt ] && echo ">> Please fill in all required variabled -- Edit '/etc/getnewip/units/$configFile'." && exit 1
 	return 1
 else
+	[ ! "${#dropboxAppKey}" = 64 ] && echo ">> Dropbox key invalid." && return 1
+	[[ ! $portCheckTimeOut =~ $digit ]] && echo ">> 'portCheckTimeOut' must be a number." && return 1
+	if ! connectionTest
+	then
+		echo ">> Cannot reach '$pingServer'."
+		return 1
+	fi
+	for port in ${localTestPorts[@]}
+	do
+		[[ ! $port =~ $digit ]] && return 1
+	done
 	for user in ${includedUsers[@]}
-	do		
-		if ! echo $users | grep -q $user
+	do
+		homeDir=$(echo $(getent passwd $user ) | cut -d : -f 6)
+		if ! echo $users | grep -q -w $user
 		then
 			echo ">> Could not find user '$user'."
 			return 1
 		else
 			for host in ${SSHcfgHost[@]}
 			do
-				! grep -q $host /home/$user/.ssh/config && echo ">> Cannot find SSH config file for user '$user'." && return 1
+				! grep -q -w $host $homeDir/.ssh/config && echo ">> Cannot find SSH config file for user '$user'." && return 1
 			done
 		fi
 	done
@@ -264,22 +337,18 @@ function configLoad() {
 local configFiles
 configFiles="$@"
 
-echo ${configFiles[@]} | grep -q 'getnewip-example' && helpMenu config
+echo ${configFiles[@]} | grep -q -w 'getnewip-example' && helpMenu config
 
 for configFile in $configFiles
 do
-	if ! echo $configFile | grep -q ".conf"
-	then
-		configFile="$configFile.conf"
-	fi
+	! echo $configFile | grep -q ".conf" && configFile="$configFile.conf"
 
 	if [ -f /etc/getnewip/units/$configFile ]
 	then
 		cleanVariables
 		echo "> Loading config '$configFile'."
 		. /etc/getnewip/units/$configFile
-		variableCheck
-		main
+		variableCheck && main || echo "> Unit config variables not OK. Please fix stated problem with unit config."
 	else
 		echo ">> Config '$configFile' not found."
 	fi
@@ -287,28 +356,14 @@ done
 
 }
 
-function cleanVariables() {
-# clean variables between checks
-
-localReferenceDevice=''
-localTestPorts=()
-portCheckTimeOut=
-pingServer=''
-SSHcfgHost=('')
-dropboxFolder=''
-gniUnit=''
-dropboxAppKey=''
-includedUsers=('')
-
-}
-
 function listConfigUnits() {
+# list all available units' config files
 
 local unit opt out counter
 opt=$@
 counter=0
 
-[ ! -d /etc/getnewip/units ] && echo ">> Failed to find units folder."
+[ ! -d /etc/getnewip/units ] && echo ">> Failed to find units folder." && exit 1
 
 for unit in $(ls /etc/getnewip/units)
 do
@@ -321,7 +376,6 @@ then
 	if [ $counter = 0 ]
 	then
 		echo ">> No units available. Please create one. 'getnewip -h config' for help, 'getnewip -m' to make one."
-
 	elif [ $counter = 1 ]
 	then
 		echo "$counter available unit: $out"
@@ -349,7 +403,7 @@ fi
 nano $tempFile
 
 echo "
-	0) Re-[e]dit config file again.
+	0) [E]dit config file again.
 	1) [R]estart.
 	2) [S]ave and exit.
 	q) [Q]uit without saving.
@@ -370,7 +424,7 @@ case $continuevar in
 
 	2|s|S)
 		if . $tempFile && variableCheck a
-		then	
+		then
 			$sudoProg install -g $user -o $user -m 0600 $tempFile /etc/getnewip/units/$gniUnit.conf && echo "> Config '$gniUnit' saved." && exit 0
 			echo ">> Failed to write config." && [ -f $tempFile ] && rm $tempFile && echo "> Cleaned up temporary files."  && exit 1
 		else
@@ -383,6 +437,59 @@ case $continuevar in
 		exit 0
 	;;
 esac
+
+}
+
+function checkSettings() {
+# check /etc/getnewip/getnewip-settings.conf
+
+if ${loopDelayTime+"false"} || [ -z $loopDelayTime ] || [ -z $curlTimeoutTime ]
+then
+	echo ">> Cannot find important config data." && exit 1
+fi
+
+local unit
+if ! [[ -z ${disabledUnits[@]} ]]
+then
+	for unit in ${disabledUnits[@]}
+	do
+		[ ! -f /etc/getnewip/units/$unit.conf ] && echo ">> Cannot find unit '$unit' to disable. Ignoring..."
+	done
+fi
+
+! [[ $loopDelayTime =~ [0-9] ]] && echo ">> Variable 'loopDelayTime' must only contain numbers." && exit 1
+! [[ $curlTimeoutTime =~ [0-9] ]] && echo ">> Variable 'curlTimeoutTime' must only contain numbers." && exit 1
+
+}
+
+function removeUnit() {
+# remove a given unit
+local unitFiles unit unitFullFileName
+unitFiles=$@
+
+[[ -z $unitFiles ]] && echo ">> No configs given to remove. Run 'getnewip -l' for a list of units" && exit 1
+
+for unit in $unitFiles
+do
+	unitFullFileName=$unit
+	! echo $unitFullFileName | grep -q ".conf" && unitFullFileName="$unitFullFileName.conf"
+	if [ -f /etc/getnewip/units/$unitFullFileName ]
+	then
+		echo "> Removing unit '$unit'."
+		if rm -v /etc/getnewip/units/$unitFullFileName
+		then
+			echo "> Unit '$unit' removed."
+			echo "> Finished removal of unit '$unit'!"
+			exit 0
+		else
+			echo ">> Failed to remove unit '$unit'."
+			exit 1
+		fi
+	else
+		echo ">> Could not find unit '$unit'."
+		exit 1
+	fi
+done
 
 }
 
@@ -427,13 +534,14 @@ exit
 if [ -f /etc/getnewip/getnewip-settings.conf ]
 then
 	. /etc/getnewip/getnewip-settings.conf
+	checkSettings
 else
 	echo ">> Missing settings config file. Please reinstall."
 	helpMenu
 	exit 1
 fi
 
-if id | grep -q sudo && which sudo > /dev/null
+if id | grep -q -w sudo && which sudo > /dev/null
 then
 	sudoProg="sudo"
 
@@ -442,7 +550,7 @@ then
 	sudoProg=""
 else
 	echo ">> You must be in sudoers or be root to use some this program."
-	exit
+	exit 1
 fi
 
 optCount=0
@@ -458,7 +566,7 @@ case "$givenOpt" in
 		startMain "$@"
 	;;
 
-	-s|--service)
+	-d|--daemonise|--daemonize)
 		# service mode, run as loop.
 		shift
 		readonly isLooped=true
@@ -469,7 +577,7 @@ case "$givenOpt" in
 	;;
 
 	-t|--testmode)
-		# fetch IP regardless, once.		
+		# fetch IP regardless, once.
 		shift
 		readonly isLooped=false
 		readonly fetchIPNoCheck=false
@@ -478,20 +586,29 @@ case "$givenOpt" in
 	;;
 
 	-l|--list)
+		# list all available units.
 		listConfigUnits
 	;;
 
-	-m|--make)
+	-m|--make-unit)
+		# create a unit.
 		makeNewConfigUnit
 	;;
 
+	-r|--remove)
+		shift
+		removeUnit "$@"
+	;;
+
 	-h|--help)
+		# print help menu(s).
 		shift
 		helpMenu "$@"
 		exit
 	;;
 
 	*)
+		# if not args are given, show help.
 		helpMenu
 		[[ $(listConfigUnits a) = "" ]] && listConfigUnits
 	;;
